[[redirects]]
from = "/home"
to = "/"
status = 200

[[redirects]]
from = "/main"
to = "/st"
status = 200

[[redirects]]
from = "/s/"
to = "/playlist"
force = true
status = 200

[[redirects]]
from = "/c/"
to = "/cs"
force = true
status = 301

[[redirects]]
from = "/s/zxpl.css"
to = "/css/zxpl.css"
status = 200

[[redirects]]
from = "/index"
to = "/"
status = 200

[[redirects]]
from = "/*"
to = "/404"
status = 404
